project_id = "wcdplljxjuyacpkbipwu"

[functions.notify-admin]
verify_jwt = false

[functions.approve-user]
verify_jwt = false

[functions.send-verification-email]
verify_jwt = false

[functions.verify-email]
verify_jwt = false

[functions.cloudinary-upload]
verify_jwt = false

[functions.migrate-to-cloudinary]
verify_jwt = false
